### ISSUE TITLE
Dependency on astrea.helio SPARQL endpoint which seems to be down

### ISSUE THREAD

**Issue by SvenLieber** [oeg-upm/astrea#11]
Hello,

I tried to generate shapes from an ontology using https://astrea.linkeddata.es/, but the only content I got was the following:

```turtle
<http://astrea.linkeddata.es/report>
        a       <https://w3id.org/def/astrea#ShapeReport> ;
        <https://w3id.org/def/astrea#generatedShapesFrom>
                <https://astrea.linkeddata.es/report/0620946147> .

<https://astrea.linkeddata.es/report/0620946147>
        a       <https://w3id.org/def/astrea#ReportEntry> ;
        <https://w3id.org/def/astrea#message>
                "Shapes generated with no errors" ;
        <https://w3id.org/def/astrea#statusCode>
                "200"^^<http://www.w3.org/2001/XMLSchema#int> .
```
The same happens for the catalogue you provide (the shape files for the different ontologies are all empty besides the shown report message).

I checked out this repo, compiled it and tried to run Astrea locally. But I got the following error:

```
Aug 19, 2021 4:02:18 PM astrea.generators.OwlGenerator fetchQueries
WARNING: Likely provided endpoint is not available, endpoint=https://astrea.helio.linkeddata.es/sparql
```

It seems that also the local version relies on a SPARQL endpoint which seems to be down.

**Comment by AndreaCimminoArriaga** [comment]
Hello @SvenLieber, thanks for the issue. Astrea relies on a set of mappings in order to generate the shapes, these mappings are published by a third party service which endpoint is https://astrea.helio.linkeddata.es/sparql. Nevertheless, the code can be ran locally and such endpoint modified; so it can be used a local SPARQL endpoint or even a file containing the mappings.

During summer we had some issues with the server and the https://astrea.helio.linkeddata.es/sparql service was down. Due to that reason Astrea was generating empty shapes. I fixed and relaunched the services, everything should work fine now.

I'm going to close the issue since everything works fine, but please let me know if anything else come along. Many thanks, I really appreciate your issue.
